using Smb.Core.Shared;
using System;
using System.Runtime.InteropServices;

namespace Smb.Core.Messages
{
    /// <summary>
    /// The SMB2 NEGOTIATE Request packet is used by the client to notify the server what dialects of the SMB 2 Protocol the client understands. This request is composed of an SMB2 header, as specified in section 2.2.1
    /// </summary>
    [StructLayout(layoutKind: LayoutKind.Sequential, Pack = 1)]
    internal class NEGOTIATE_Request
    {
        /// <summary>
        /// StructureSize (2 bytes): The client MUST set this field to 36, indicating the size of a NEGOTIATE request. This is not the size of the structure with a single dialect in the Dialects[] array. This value MUST be set regardless of the number of dialects or number of negotiate contexts sent.
        /// </summary>
        public UInt16 StructureSize => 36;
        /// <summary>
        /// DialectCount (2 bytes): The number of dialects that are contained in the Dialects[] array. This value MUST be greater than 0.<7>
        /// </summary>
        public UInt16 DialectCount => 64;
        /// <summary>
        /// SecurityMode (2 bytes): The security mode field specifies whether SMB signing is enabled or required at the client
        /// </summary>
        public NegotiateSecurityModes SecurityMode;
        /// <summary>
        /// Reserved (2 bytes): The client MUST set this to 0, and the server SHOULD<8> ignore it on receipt.
        /// </summary>
        public UInt16 Reserved => 0;
        /// <summary>
        /// Capabilities (4 bytes): If the client implements the SMB 3.x dialect family, the Capabilities field MUST be constructed using the following values. 
        /// Otherwise, this field MUST be set to 0.
        /// </summary>
        public NegotiateCapabilities Capabilities;
        /// <summary>
        /// ClientGuid (16 bytes): It MUST be a GUID (as specified in [MS-DTYP] section 2.3.4.2) generated by the client.
        /// </summary>
        public Guid ClientGuid;
        /// <summary>
        /// (NegotiateContextOffset/NegotiateContextCount/Reserved2)/ClientStartTime (8 bytes): This field is interpreted in different ways depending on the SMB2 Dialects field.
        /// </summary>
        public NegotiateDynamicContext NegotiateContext;
        /// <summary>
        /// </summary>
        public SMBDialects[] Dialects;

        /// <summary>
        /// Padding (variable): Optional padding between the end of the Dialects array and the first negotiate context in NegotiateContextList so that the first negotiate context is 8-byte aligned.
        /// </summary>
        public Byte[] Padding;
        /// <summary>
        /// NegotiateContextList (variable): If the Dialects field contains 0x0311, then this field will contain an array of SMB2 NEGOTIATE_CONTEXTs. The first negotiate context in the list MUST appear at the byte offset indicated by the SMB2 NEGOTIATE request's NegotiateContextOffset field. Subsequent negotiate contexts MUST appear at the first 8-byte-aligned offset following the previous negotiate context.
        /// </summary>
        public ICapability[] NegotiateContextList; 
    }
}
